# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://jawang94.github.io/
title: Jason W.
email: wang.jason.010@gmail.com
author: Jason Wang
description: > # "Jason Wang's Personal Page"

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty
# Build sitemap
gems:
  - jekyll-sitemap

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - icon: medium
    title: medium
    url: https://medium.com/@wjason
  - icon: envelope-o
    title: email
    url: mailto:wang.jason.010@gmail.com
  - icon: github
    title: github
    url: https://github.com/jawang94
  - icon: linkedin
    title: linkedin
    url: https://www.linkedin.com/in/jasonwang94/
  - icon: file-pdf-o
    title: resume
    url: https://jasonw.tech/rsc/CurrentResume.pdf
  - icon: window-maximum
    title: guidelyte
    url: https://guidelyte.com
