# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://jawang94.github.io/
title: Jason W.
email: jason.wang@psu.edu
author: Jason Wang
description: > # "Jason Wang's Personal Page"


# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty
# Build sitemap
gems:
  - jekyll-sitemap

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - icon: caret-square-o-right
    title: devpost
    url: https://devpost.com/jawang94?ref_content=user-portfolio&ref_feature=portfolio&ref_medium=global-nav
  - icon: envelope-o
    title: email
    url: mailto:jason.wang@psu.edu
  - icon: github
    title: github
    url: https://github.com/jawang94
  - icon: linkedin
    title: linkedin
    url: https://www.linkedin.com/in/jasonwang94/
  - icon: file-pdf-o
    title: resume
    url: https://jasonw.tech/rsc/jasonWangResume.pdf
